### ISSUE TITLE
The authors guideline location on web page

### ISSUE THREAD

**Issue by vedina** [jcheminform/jcheminform-author-guidelines#4]
Wondering why the guide https://jcheminf.biomedcentral.com/submission-guidelines/preparing-your-manuscript is under Copyright ? Not intuitive to find, even when knowing the guide is on the journal page . May be just misplaced?

![image](https://user-images.githubusercontent.com/211190/54491832-29007400-48ca-11e9-9ef6-e89e92b3a46d.png)

**Comment by schymane** [comment]
I also note that this continues to be difficult to find on the JCheminf website and I am a reasonably regular visitor of the site ...

**Comment by egonw** [comment]
It's not under Copyright, but the layout is weird cause by the extra indentation caused by the "arrow" icon before "Preparing..." :/
