### ISSUE TITLE
APCs

### ISSUE THREAD

**Issue by schymane** [jcheminform/jcheminform-author-guidelines#5]
It seems that currently the one APC applies to all article types, is this correct? Even for small articles like Letter to the Editor or Commentary?

Open access publishing is not without costs. Journal of Cheminformatics therefore levies an article-processing charge of £1210.00/$1890.00/€1540.00 for each article accepted for publication, plus VAT or local taxes where applicable.

**Comment by egonw** [comment]
If not mistaken, I believe that is currently correct.

**Comment by rajarshi** [comment]
I think Letter to Editor is free of charge

**Comment by egonw** [comment]
Difficult topic, and nothing much we (editors) can do about this, and not part of the author guidelines anyway.
